### ISSUE TITLE
Setup automated tests

### ISSUE THREAD

**Issue by zdylag** [speedrun-website/leaderboard-backend#18]
As actual code gets added to this repo, it will be increasingly difficult for each PR to get downloaded locally and tested.

Instead, being able to rely on our automated test suite to tell us "this does not break anything that we know of" will make code reviews much easier and let us move faster.

**Comment by akleemans** [comment]
Totally agree. I think Github Actions are a great tool where we should set up a simple pipeline from the beginning, with building and running tests.

I don't have any experience with what is required for Go but would be glad to help with the frontend & E2E stuff.

**Comment by zdylag** [comment]
We should also maybe run `go mod tidy` and verify it does not change anything, as one of the lint-y steps.

**Comment by weilianchu** [comment]
Going to take a stab at this w/ Github Actions! Will be my first time playing around with it tho, so if anyone wants to do it faster, they should feel free.
