### ISSUE TITLE
Create git / contribution Guidelines

### ISSUE THREAD

**Issue by akleemans** [speedrun-website/leaderboard-backend#32]
Set up a page or file to make it clear how to contribute (from: [this PR](https://github.com/speedrun-website/leaderboard-backend/pull/30#issuecomment-878561881))
- Commit message guidelines (for example: https://golang.org/doc/contribute#commit_messages)
- Squash vs. rebase on PR merges
- Branching (for example feature/*, bugfix/*-branches, Gitflow)

**Comment by akleemans** [comment]
(probably part of https://github.com/speedrun-website/leaderboard-backend/issues/22 - but this might be a good one to tackle early)

**Comment by Matt-Hurd** [comment]
I suck at this sort of thing. If someone can champion this, I'm more than happy to follow whatever guidelines they add.
My only really small thing is that I don't like having `/` in branch names (on the main repo at least). They don't really work well under-the-hood in git at times.
